# Usa uma imagem base oficial do Node.js
FROM node:18

# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copia os arquivos de dependências do Node.js
COPY package.json package-lock.json ./

# Instala as dependências
RUN npm install

# Copia os arquivos da aplicação para o container
COPY . .

# Expõe a porta que o aplicativo usa
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["npm", "start"]
